# Generated by Django 4.2.1 on 2023-05-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('opis', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sastojak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('V', 'Voce'), ('P', 'Povrce'), ('M', 'Meso'), ('Z', 'Zitarice'), ('L', 'Mijecni'), ('B', 'Biljni'), ('O', 'Ostali')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SastojakRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceptiApp.recept')),
                ('sastojak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReceptiApp.sastojak')),
            ],
        ),
    ]
