# Generated by Django 4.2.1 on 2023-05-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptiApp', '0003_sastojakrecept_dodatni_info_sastojakrecept_kolicina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='vrijeme_pripreme',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
