# Generated by Django 4.2.1 on 2023-05-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptiApp', '0004_recept_vrijeme_pripreme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sastojak',
            name='tip',
            field=models.CharField(choices=[('V', 'Voce'), ('P', 'Povrce'), ('M', 'Meso'), ('Z', 'Zitarice'), ('L', 'Mlijeko i jaja'), ('B', 'Biljni i zacini'), ('U', 'Ulje i masti'), ('O', 'Ostali')], default='O', max_length=1),
        ),
    ]
