# Generated by Django 4.2.1 on 2023-05-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptiApp', '0005_alter_sastojak_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='sastojci',
            field=models.ManyToManyField(through='ReceptiApp.SastojakRecept', to='ReceptiApp.sastojak'),
        ),
    ]
