# Generated by Django 4.2.1 on 2023-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceptiApp', '0012_komentar_recept'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='uputa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
